# -*- mode: python ; coding: utf-8 -*-
# main.spec — LOGIPORT
# =====================

block_cipher = None

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('icons', 'icons'),
        ('config', 'config'),
        ('core/i18n/ar.py', 'core/i18n'),
        ('core/i18n/en.py', 'core/i18n'),
        ('core/i18n/tr.py', 'core/i18n'),
        ('core/i18n/__init__.py', 'core/i18n'),
        ('documents/templates', 'documents/templates'),
        ('documents/static', 'documents/static'),
        ('documents/builders', 'documents/builders'),
        ('documents/__init__.py', 'documents'),
        ('documents/registry.py', 'documents'),
        ('data/avatars', 'data/avatars'),
    ],
    hiddenimports=[
        # PySide6
        'PySide6.QtCore',
        'PySide6.QtGui',
        'PySide6.QtWidgets',
        'PySide6.QtPrintSupport',
        'PySide6.QtSvg',
        'PySide6.QtWebEngineCore',
        'PySide6.QtWebEngineWidgets',

        # SQLAlchemy
        'sqlalchemy',
        'sqlalchemy.orm',
        'sqlalchemy.orm.session',
        'sqlalchemy.dialects.sqlite',
        'sqlalchemy.dialects.sqlite.pysqlite',
        'sqlalchemy.sql.default_comparator',
        'sqlalchemy.event',
        'sqlalchemy.pool',
        'database.models.task',
        'database.crud.tasks_crud',
        'sqlalchemy.engine',
        'sqlalchemy.engine.url',

        # Jinja2
        'jinja2',
        'jinja2.ext',
        'jinja2.loaders',
        'markupsafe',

        # bcrypt / passlib
        'bcrypt',
        'passlib',
        'passlib.handlers',
        'passlib.handlers.bcrypt',

        # openpyxl
        'openpyxl',
        'openpyxl.styles',
        'openpyxl.utils',

        # dotenv
        'dotenv',

        # stdlib
        'pkgutil',
        'importlib.util',
        'importlib.machinery',
        'concurrent.futures',
        'logging.handlers',

        # UI Tabs
        'ui.tabs.admin_dashboard_tab',
        'ui.tabs.audit_trail_tab',
        'ui.tabs.clients_tab',
        'ui.tabs.companies_tab',
        'ui.tabs.container_tracking_tab',
        'ui.tabs.countries_tab',
        'ui.tabs.currencies_tab',
        'ui.tabs.dashboard_tab',
        'ui.tabs.delivery_methods_tab',
        'ui.tabs.documents_tab',
        'ui.tabs.entries_tab',
        'ui.tabs.material_types_tab',
        'ui.tabs.materials_tab',
        'ui.tabs.packaging_types_tab',
        'ui.tabs.permissions_tab',
        'ui.tabs.pricing_tab',
        'ui.tabs.transactions_tab',
        'ui.tabs.user_profile_tab',
        'ui.tabs.users_permissions_tab',
        'ui.tabs.offices_tab',
        'ui.tabs.users_tab',
        'ui.tabs.values_tab',
        'ui.tabs.tasks_tab',

        # UI Dialogs
        'ui.dialogs.about_dialog',
        'ui.dialogs.global_search_dialog',
        'ui.dialogs.add_TransactionWindow.window',
        'ui.dialogs.add_client_dialog',
        'ui.dialogs.add_company_dialog',
        'ui.dialogs.add_country_dialog',
        'ui.dialogs.add_currency_dialog',
        'ui.dialogs.add_delivery_method_dialog',
        'ui.dialogs.add_edit_container_dialog',
        'ui.dialogs.add_entry_dialog',
        'ui.dialogs.add_material_dialog',
        'ui.dialogs.add_material_type_dialog',
        'ui.dialogs.add_packaging_type_dialog',
        'ui.dialogs.add_office_dialog',
        'ui.dialogs.add_pricing_dialog',
        'ui.dialogs.add_role_dialog',
        'ui.dialogs.client_contacts_dialog',
        'ui.dialogs.company_banks_dialog',
        'ui.dialogs.company_partners_dialog',
        'ui.dialogs.entries_picker_dialog',
        'ui.dialogs.generate_document_dialog',
        'ui.dialogs.task_dialog',
        'ui.dialogs.manual_item_dialog',
        'ui.dialogs.mixins.documents_tab',
        'ui.dialogs.mixins.general_tab',
        'ui.dialogs.mixins.items_tab',
        'ui.dialogs.mixins.parties_geo_tab',
        'ui.dialogs.mixins.transport_tab',
        'ui.dialogs.pick_entries_dialog',
        'ui.dialogs.sync_settings_dialog',
        'ui.dialogs.update_dialog',
        'ui.dialogs.users_dialogs',
        'ui.dialogs.view_details._view_helpers',
        'ui.dialogs.view_details.view_client_dialog',
        'ui.dialogs.view_details.view_company_dialog',
        'ui.dialogs.view_details.view_container_dialog',
        'ui.dialogs.view_details.view_country_dialog',
        'ui.dialogs.view_details.view_currency_dialog',
        'ui.dialogs.view_details.view_delivery_method_dialog',
        'ui.dialogs.view_details.view_entry_dialog',
        'ui.dialogs.view_details.view_material_dialog',
        'ui.dialogs.view_details.view_material_type_dialog',
        'ui.dialogs.view_details.view_office_dialog',
        'ui.dialogs.view_details.view_packaging_type_dialog',
        'ui.dialogs.view_details.view_pricing_dialog',
        'ui.dialogs.view_details.view_role_dialog',
        'ui.dialogs.view_details.view_transaction_dialog',
        'ui.dialogs.view_details.view_user_dialog',

        # UI Widgets
        'ui.login_window',
        'ui.main_window',
        'ui.settings_window',
        'ui.setup_wizard',
        'ui.widgets.custom_button',
        'ui.widgets.custom_table',
        'ui.widgets.notification_bell',
        'ui.widgets.pdf_preview_dialog',
        'ui.widgets.container_timeline',
        'ui.widgets.container_timeline',
        'ui.widgets.searchable_combo',
        'ui.widgets.sidebar',
        'ui.widgets.sync_widget',
        'ui.widgets.topbar',

        # UI Utils
        'ui.utils',
        'ui.utils.svg_icons',
        'ui.utils.field_navigation',
        'ui.utils.wheel_blocker',
        'ui.utils.__init___utils',

        # Utils
        'utils.auth_utils',
        'utils.password_utils',
        'utils.paths',
        'utils.user_utils',

        # Core
        'core.admin_columns',
        'core.base_details_view',
        'core.base_dialog',
        'core.base_tab',
        'core.base_window',
        'core.config',
        'core.form_dialog',
        'core.i18n.ar',
        'core.i18n.en',
        'core.i18n.tr',
        'core.logging_config',
        'core.office_context',
        'core.paths',
        'core.permissions',
        'core.settings_manager',
        'core.singleton',
        'core.theme_manager',
        'core.translator',

        # Database
        'database.audit_helper',
        'database.bootstrap',
        'database.crud.audit_log_crud',
        'database.crud.base_crud',
        'database.crud.clients_crud',
        'database.crud.companies_crud',
        'database.crud.company_roles_crud',
        'database.crud.container_tracking_crud',
        'database.crud.countries_crud',
        'database.crud.currencies_crud',
        'database.crud.delivery_methods_crud',
        'database.crud.document_types_crud',
        'database.crud.documents_crud',
        'database.crud.entries_crud',
        'database.crud.material_types_crud',
        'database.crud.materials_crud',
        'database.crud.offices_crud',
        'database.crud.packaging_types_crud',
        'database.crud.permissions_crud',
        'database.crud.pricing_crud',
        'database.crud.pricing_types_crud',
        'database.crud.transactions_crud',
        'database.crud.users_crud',
        'database.db_utils',
        'database.mappers.document_mapper',
        'database.mixins',
        'database.models.audit_log',
        'database.models.base',
        'database.models.client',
        'database.models.company',
        'database.models.company_role',
        'database.models.container_tracking',
        'database.models.country',
        'database.models.currency',
        'database.models.delivery_method',
        'database.models.document',
        'database.models.document_group',
        'database.models.document_type',
        'database.models.entry',
        'database.models.entry_item',
        'database.models.material',
        'database.models.material_type',
        'database.models.office',
        'database.models.packaging_type',
        'database.models.permission',
        'database.models.pricing',
        'database.models.pricing_type',
        'database.models.role',
        'database.models.role_permission',
        'database.models.sync_models',
        'database.models.transaction',
        'database.models.transaction_item',
        'database.models.transport_details',
        'database.models.user',
        'database.models.utils',

        # Services
        'services.backup_service',
        'services.builder_router',
        'services.container_report_service',
        'services.excel_service',
        'services.exceptions',
        'services.facade',
        'services.global_search_service',
        'services.healthcheck',
        'services.html_engine',
        'services.notification_service',
        'services.alert_service',
        'services.numbering_service',
        'services.pdf_renderer',
        'services.persist_generated_doc',
        'services.pricing_service',
        'services.storage_service',
        'services.supabase_client',
        'services.sync_service',
        'services.tafqit_service',
        'services.updater_service',

        # config / themes
        'config.settings',
        'config.themes',
        'config.themes.builder',
        'config.themes.palettes',
        'config.themes.presets.dark',
        'config.themes.presets.light',
        'config.themes.semantic_colors',
        'config.themes.border_radius',
        'config.themes.spacing',
        'config.themes.typography',
        'config.themes.components',
        'config.themes.components.base',
        'config.themes.components.buttons',
        'config.themes.components.cards',
        'config.themes.components.forms',
        'config.themes.components.tables',
        'config.themes.components.dialogs',
        'config.themes.components.sidebar',
        'config.themes.components.topbar',
        'config.themes.components.misc',
        'config.themes.components.tabs',
        'config.themes.components.details_view',
        'config.themes.components.dashboard_profile',
        'config.themes.components.transaction_styles',
        'packaging', 'packaging.version',

    ],
    hookspath=['hooks'],
    runtime_hooks=['hooks/runtime_i18n.py'],
    excludes=[
        'pytest',
        'unittest',
        'tkinter',
        'matplotlib',
        'numpy',
        'pandas',
        'PIL',
        'wx',
        'weasyprint',
        'cairocffi',
    ],
    noarchive=False,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='LOGIPORT',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    console=False,
    icon='icons/logo.ico',
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=False,
    upx_exclude=[],
    name='LOGIPORT',
)
