"""baseline_initial_schema

Revision ID: 4f425d1a4c0a
Revises: 
Create Date: 2026-02-22 12:22:23.755440

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f425d1a4c0a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name_ar', sa.String(length=255), nullable=False),
    sa.Column('name_en', sa.String(length=255), nullable=True),
    sa.Column('name_tr', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='100', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('company_roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_roles_code'), ['code'], unique=True)

    op.create_table('delivery_methods',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name_ar', sa.String(length=255), nullable=False),
    sa.Column('name_en', sa.String(length=255), nullable=True),
    sa.Column('name_tr', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='100', nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('name_ar', sa.Text(), nullable=True),
    sa.Column('name_en', sa.Text(), nullable=True),
    sa.Column('name_tr', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.Column('group_code', sa.Text(), nullable=True),
    sa.Column('template_path', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_document_types_code')
    )
    with op.batch_alter_table('document_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_types_code'), ['code'], unique=True)
        batch_op.create_index('ix_document_types_group_code', ['group_code'], unique=False)

    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('label_ar', sa.String(length=100), nullable=True),
    sa.Column('label_en', sa.String(length=100), nullable=True),
    sa.Column('label_tr', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('pricing_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('name_ar', sa.String(), nullable=True),
    sa.Column('name_en', sa.String(), nullable=True),
    sa.Column('name_tr', sa.String(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('compute_by', sa.String(), nullable=True),
    sa.Column('price_unit', sa.String(), nullable=True),
    sa.Column('divisor', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pricing_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pricing_types_code'), ['code'], unique=False)

    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('label_ar', sa.String(length=50), nullable=True),
    sa.Column('label_en', sa.String(length=50), nullable=True),
    sa.Column('label_tr', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('document_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_type_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.Text(), nullable=False),
    sa.Column('version', sa.Text(), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_type_id'], ['document_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id'),
    sa.UniqueConstraint('role_id', 'permission_id', name='uq_role_permission')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('table_name', sa.String(length=50), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('before_data', sa.Text(), nullable=True),
    sa.Column('after_data', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('countries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_ar', sa.String(length=128), nullable=False),
    sa.Column('name_en', sa.String(length=128), nullable=False),
    sa.Column('name_tr', sa.String(length=128), nullable=False),
    sa.Column('code', sa.String(length=8), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('currencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_ar', sa.String(length=64), nullable=False),
    sa.Column('name_en', sa.String(length=64), nullable=False),
    sa.Column('name_tr', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.String(length=8), nullable=True),
    sa.Column('code', sa.String(length=8), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('material_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_ar', sa.String(length=128), nullable=False),
    sa.Column('name_en', sa.String(length=128), nullable=False),
    sa.Column('name_tr', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('packaging_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_ar', sa.String(length=128), nullable=False),
    sa.Column('name_en', sa.String(length=128), nullable=False),
    sa.Column('name_tr', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clients',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name_ar', sa.String(length=255), nullable=False),
    sa.Column('name_en', sa.String(length=255), nullable=True),
    sa.Column('name_tr', sa.String(length=255), nullable=True),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.Column('city', sa.String(length=128), nullable=True),
    sa.Column('address_ar', sa.Text(), nullable=True),
    sa.Column('address_en', sa.Text(), nullable=True),
    sa.Column('address_tr', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('default_currency_id', sa.Integer(), nullable=True),
    sa.Column('default_delivery_method_id', sa.Integer(), nullable=True),
    sa.Column('default_packaging_type_id', sa.Integer(), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('tax_id', sa.String(length=128), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['default_currency_id'], ['currencies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.create_index('idx_clients_country', ['country_id'], unique=False)
        batch_op.create_index('idx_clients_currency', ['default_currency_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clients_code'), ['code'], unique=True)

    op.create_table('materials',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name_ar', sa.String(length=255), nullable=False),
    sa.Column('name_en', sa.String(length=255), nullable=True),
    sa.Column('name_tr', sa.String(length=255), nullable=True),
    sa.Column('material_type_id', sa.Integer(), nullable=False),
    sa.Column('estimated_price', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('currency_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['currency_id'], ['currencies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['material_type_id'], ['material_types.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.create_index('idx_materials_currency', ['currency_id'], unique=False)
        batch_op.create_index('idx_materials_type', ['material_type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_materials_code'), ['code'], unique=True)

    op.create_table('client_contacts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role_title', sa.String(length=128), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('client_contacts', schema=None) as batch_op:
        batch_op.create_index('idx_contacts_primary', ['is_primary'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_contacts_client_id'), ['client_id'], unique=False)

    op.create_table('companies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name_ar', sa.String(length=255), nullable=False),
    sa.Column('name_en', sa.String(length=255), nullable=True),
    sa.Column('name_tr', sa.String(length=255), nullable=True),
    sa.Column('owner_client_id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.Column('city', sa.String(length=128), nullable=True),
    sa.Column('address_ar', sa.Text(), nullable=True),
    sa.Column('address_en', sa.Text(), nullable=True),
    sa.Column('address_tr', sa.Text(), nullable=True),
    sa.Column('default_currency_id', sa.Integer(), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('tax_id', sa.String(length=128), nullable=True),
    sa.Column('registration_number', sa.String(length=128), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['default_currency_id'], ['currencies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['owner_client_id'], ['clients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.create_index('idx_companies_active', ['is_active'], unique=False)
        batch_op.create_index('idx_companies_country', ['country_id'], unique=False)
        batch_op.create_index('idx_companies_owner', ['owner_client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_companies_owner_client_id'), ['owner_client_id'], unique=False)

    op.create_table('entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entry_no', sa.String(length=50), nullable=True),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('transport_unit_type', sa.String(length=16), nullable=True),
    sa.Column('transport_ref', sa.String(length=64), nullable=True),
    sa.Column('seal_no', sa.String(length=64), nullable=True),
    sa.Column('owner_client_id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_client_id'], ['clients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entry_no')
    )
    with op.batch_alter_table('entries', schema=None) as batch_op:
        batch_op.create_index('idx_entries_date', ['entry_date'], unique=False)
        batch_op.create_index('idx_entries_transport', ['transport_unit_type', 'transport_ref'], unique=False)
        batch_op.create_index(batch_op.f('ix_entries_owner_client_id'), ['owner_client_id'], unique=False)

    op.create_table('company_banks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('bank_name', sa.String(length=255), nullable=True),
    sa.Column('branch', sa.String(length=255), nullable=True),
    sa.Column('beneficiary_name', sa.String(length=255), nullable=True),
    sa.Column('iban', sa.String(length=64), nullable=True),
    sa.Column('swift_bic', sa.String(length=64), nullable=True),
    sa.Column('account_number', sa.String(length=64), nullable=True),
    sa.Column('bank_country_id', sa.Integer(), nullable=True),
    sa.Column('currency_id', sa.Integer(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['bank_country_id'], ['countries.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['currency_id'], ['currencies.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('company_banks', schema=None) as batch_op:
        batch_op.create_index('idx_company_banks_company', ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_company_banks_company_id'), ['company_id'], unique=False)

    op.create_table('company_partner_links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('partner_role', sa.String(length=128), nullable=True),
    sa.Column('share_percent', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'client_id', name='uq_company_partner')
    )
    with op.batch_alter_table('company_partner_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_partner_links_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_company_partner_links_company_id'), ['company_id'], unique=False)

    op.create_table('company_role_links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['company_roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('company_role_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_role_links_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_company_role_links_role_id'), ['role_id'], unique=False)

    op.create_table('entry_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('packaging_type_id', sa.Integer(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('net_weight_kg', sa.Float(), nullable=True),
    sa.Column('gross_weight_kg', sa.Float(), nullable=True),
    sa.Column('mfg_date', sa.Date(), nullable=True),
    sa.Column('exp_date', sa.Date(), nullable=True),
    sa.Column('origin_country_id', sa.Integer(), nullable=True),
    sa.Column('batch_no', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['entry_id'], ['entries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['origin_country_id'], ['countries.id'], ),
    sa.ForeignKeyConstraint(['packaging_type_id'], ['packaging_types.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('entry_items', schema=None) as batch_op:
        batch_op.create_index('idx_entry_items_entry', ['entry_id'], unique=False)
        batch_op.create_index('idx_entry_items_material', ['material_id'], unique=False)
        batch_op.create_index('idx_entry_items_origin', ['origin_country_id'], unique=False)

    op.create_table('pricing',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('seller_company_id', sa.Integer(), nullable=False),
    sa.Column('buyer_company_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('pricing_type_id', sa.Integer(), nullable=False),
    sa.Column('currency_id', sa.Integer(), nullable=False),
    sa.Column('delivery_method_id', sa.Integer(), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['buyer_company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['currency_id'], ['currencies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['delivery_method_id'], ['delivery_methods.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['pricing_type_id'], ['pricing_types.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['seller_company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pricing', schema=None) as batch_op:
        batch_op.create_index('idx_pricing_key', ['seller_company_id', 'buyer_company_id', 'material_id', 'pricing_type_id', 'currency_id', 'is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_pricing_buyer_company_id'), ['buyer_company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pricing_currency_id'), ['currency_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pricing_material_id'), ['material_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pricing_pricing_type_id'), ['pricing_type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pricing_seller_company_id'), ['seller_company_id'], unique=False)

    op.create_table('transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transaction_no', sa.String(length=32), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('transaction_type', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('exporter_company_id', sa.Integer(), nullable=False),
    sa.Column('importer_company_id', sa.Integer(), nullable=False),
    sa.Column('relationship_type', sa.String(length=32), nullable=True),
    sa.Column('broker_company_id', sa.Integer(), nullable=True),
    sa.Column('origin_country_id', sa.Integer(), nullable=True),
    sa.Column('dest_country_id', sa.Integer(), nullable=True),
    sa.Column('currency_id', sa.Integer(), nullable=True),
    sa.Column('pricing_type_id', sa.Integer(), nullable=True),
    sa.Column('delivery_method_id', sa.Integer(), nullable=True),
    sa.Column('transport_type', sa.String(length=16), nullable=True),
    sa.Column('transport_ref', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('totals_count', sa.Float(), nullable=True),
    sa.Column('totals_gross_kg', sa.Float(), nullable=True),
    sa.Column('totals_net_kg', sa.Float(), nullable=True),
    sa.Column('totals_value', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['broker_company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['currency_id'], ['currencies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['delivery_method_id'], ['delivery_methods.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['dest_country_id'], ['countries.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['exporter_company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['importer_company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['origin_country_id'], ['countries.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['pricing_type_id'], ['pricing_types.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_transaction_no'), ['transaction_no'], unique=True)

    op.create_table('doc_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('doc_no', sa.Text(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year', 'month', 'seq', name='uq_doc_groups_ym_seq')
    )
    with op.batch_alter_table('doc_groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_doc_groups_doc_no'), ['doc_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_doc_groups_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('transaction_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['entries.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id', 'entry_id', name='uq_transaction_entry')
    )
    with op.batch_alter_table('transaction_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transaction_entries_entry_id'), ['entry_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_entries_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('transaction_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=True),
    sa.Column('entry_item_id', sa.Integer(), nullable=True),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('packaging_type_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('gross_weight_kg', sa.Float(), nullable=True),
    sa.Column('net_weight_kg', sa.Float(), nullable=True),
    sa.Column('pricing_type_id', sa.Integer(), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('currency_id', sa.Integer(), nullable=True),
    sa.Column('line_total', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('origin_country_id', sa.Integer(), nullable=True),
    sa.Column('source_type', sa.String(length=16), nullable=True),
    sa.Column('is_manual', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('transport_ref', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['currency_id'], ['currencies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['entry_id'], ['entries.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['entry_item_id'], ['entry_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['origin_country_id'], ['countries.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['packaging_type_id'], ['packaging_types.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['pricing_type_id'], ['pricing_types.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transaction_items', schema=None) as batch_op:
        batch_op.create_index('ix_trx_items_trx', ['transaction_id'], unique=False)

    op.create_table('documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('document_type_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.Text(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('totals_json', sa.Text(), nullable=True),
    sa.Column('totals_text', sa.Text(), nullable=True),
    sa.Column('data_json', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['document_type_id'], ['document_types.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['group_id'], ['doc_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['document_templates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_document_type_id'), ['document_type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_group_id'), ['group_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_group_id'))
        batch_op.drop_index(batch_op.f('ix_documents_document_type_id'))

    op.drop_table('documents')
    with op.batch_alter_table('transaction_items', schema=None) as batch_op:
        batch_op.drop_index('ix_trx_items_trx')

    op.drop_table('transaction_items')
    with op.batch_alter_table('transaction_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transaction_entries_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_transaction_entries_entry_id'))

    op.drop_table('transaction_entries')
    with op.batch_alter_table('doc_groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_doc_groups_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_doc_groups_doc_no'))

    op.drop_table('doc_groups')
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_transaction_no'))

    op.drop_table('transactions')
    with op.batch_alter_table('pricing', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pricing_seller_company_id'))
        batch_op.drop_index(batch_op.f('ix_pricing_pricing_type_id'))
        batch_op.drop_index(batch_op.f('ix_pricing_material_id'))
        batch_op.drop_index(batch_op.f('ix_pricing_currency_id'))
        batch_op.drop_index(batch_op.f('ix_pricing_buyer_company_id'))
        batch_op.drop_index('idx_pricing_key')

    op.drop_table('pricing')
    with op.batch_alter_table('entry_items', schema=None) as batch_op:
        batch_op.drop_index('idx_entry_items_origin')
        batch_op.drop_index('idx_entry_items_material')
        batch_op.drop_index('idx_entry_items_entry')

    op.drop_table('entry_items')
    with op.batch_alter_table('company_role_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_role_links_role_id'))
        batch_op.drop_index(batch_op.f('ix_company_role_links_company_id'))

    op.drop_table('company_role_links')
    with op.batch_alter_table('company_partner_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_partner_links_company_id'))
        batch_op.drop_index(batch_op.f('ix_company_partner_links_client_id'))

    op.drop_table('company_partner_links')
    with op.batch_alter_table('company_banks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_banks_company_id'))
        batch_op.drop_index('idx_company_banks_company')

    op.drop_table('company_banks')
    with op.batch_alter_table('entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entries_owner_client_id'))
        batch_op.drop_index('idx_entries_transport')
        batch_op.drop_index('idx_entries_date')

    op.drop_table('entries')
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_companies_owner_client_id'))
        batch_op.drop_index('idx_companies_owner')
        batch_op.drop_index('idx_companies_country')
        batch_op.drop_index('idx_companies_active')

    op.drop_table('companies')
    with op.batch_alter_table('client_contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_contacts_client_id'))
        batch_op.drop_index('idx_contacts_primary')

    op.drop_table('client_contacts')
    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_materials_code'))
        batch_op.drop_index('idx_materials_type')
        batch_op.drop_index('idx_materials_currency')

    op.drop_table('materials')
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clients_code'))
        batch_op.drop_index('idx_clients_currency')
        batch_op.drop_index('idx_clients_country')

    op.drop_table('clients')
    op.drop_table('packaging_types')
    op.drop_table('material_types')
    op.drop_table('currencies')
    op.drop_table('countries')
    op.drop_table('audit_log')
    op.drop_table('users')
    op.drop_table('role_permissions')
    op.drop_table('document_templates')
    op.drop_table('roles')
    with op.batch_alter_table('pricing_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pricing_types_code'))

    op.drop_table('pricing_types')
    op.drop_table('permissions')
    with op.batch_alter_table('document_types', schema=None) as batch_op:
        batch_op.drop_index('ix_document_types_group_code')
        batch_op.drop_index(batch_op.f('ix_document_types_code'))

    op.drop_table('document_types')
    op.drop_table('delivery_methods')
    with op.batch_alter_table('company_roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_roles_code'))

    op.drop_table('company_roles')
    # ### end Alembic commands ###
